### ISSUE TITLE
Player Movement

### ISSUE THREAD

**Issue by AdamPodoxin** [shahanneda/Rhythm-Attack#1]
I am wondering if there is a more efficient way of checking for keyboard input in the PlayerMovement script. Currently, we are checking for each individual key (WASD). I am wondering if using something like Input.GetAxisRaw would be more efficient and how we would implement something like that.

**Comment by shahanneda** [comment]
I Changed it to use Input.GetAxis(), and now it only checks the input twice instead of 4 times, though and it also feels different, but if you think it should be moved square by square like you had, we can add that easily by using a Time.deltatime check between the movements.
